#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  af7133e.o